# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-08 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='bar',
            name='name',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
